# Generated by Django 6.0.6 on 2026-06-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=255)),
                ('tahun_terbit', models.IntegerField()),
                ('rak', models.CharField(max_length=100)),
                ('stok', models.IntegerField()),
                ('deskripsi', models.TextField()),
            ],
            options={
                'db_table': 'buku',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'siswa',
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('jatuh_tempo', models.DateField()),
                ('keperluan', models.TextField()),
                ('status', models.CharField(default='Dipinjam', max_length=50)),
                ('buku', models.ForeignKey(db_column='buku_id', on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
                ('siswa', models.ForeignKey(db_column='siswa_id', on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.siswa')),
            ],
            options={
                'db_table': 'peminjaman',
            },
        ),
    ]
