# Generated by Django 6.0.6 on 2026-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='isbn',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
    ]
